AWSTemplateFormatVersion: '2010-09-09'
Description: test S3 bucket to upload images from front end 2mo (Mis Ma Ostsin) app.
#https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html

Resources:
  # S3 Bucket for Storing Receipt Images
  S3ReceiptBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 2mo-receipt-images-mismaostsin
      VersioningConfiguration:
        Status: Enabled
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
    DeletionPolicy: Delete

  # Lambda Process Receipt Function
  LambdaProcessReceipt:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ProcessReceiptLambda
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.8
      Timeout: 300
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              print('seems to be ok')  
              return {
                  "statusCode": 200,
                  "body": "Hello from Lambda"
              }

  # Lambda Execution Role for processing receipts
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3ToRDSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: 
                  - !Sub arn:aws:s3:::${S3ReceiptBucket}/*
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !GetAtt LambdaProcessReceipt.Arn

  # EventBridge Rule to Trigger Lambda on S3 Upload
  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: TriggerLambdaOnS3Upload
      EventPattern:
        Source:
          - aws.s3
        Detail:
          eventName:
            - PutObject
        Resources:
          - !Sub arn:aws:s3:::${S3ReceiptBucket}
      Targets:
        - Arn: !GetAtt LambdaProcessReceipt.Arn
          Id: TargetLambda