FROM amazonlinux:2


RUN yum groupinstall -y "Development Tools" && \
    yum install -y gcc openssl-devel bzip2-devel libffi-devel zlib-devel wget make

# Build python3.9 so it matches with the lambda runtime
RUN wget https://www.python.org/ftp/python/3.9.9/Python-3.9.9.tgz && \
    tar -xzf Python-3.9.9.tgz && \
    cd Python-3.9.9 && \
    ./configure --enable-optimizations && \
    make altinstall && \
    cd .. && \
    rm -rf Python-3.9.9*  # Clean up

# checking if Python 3.9 is installed correctly
RUN /usr/local/bin/python3.9 --version

# use Python 3.9 and upgrade it
RUN /usr/local/bin/python3.9 -m ensurepip --upgrade && \
    /usr/local/bin/python3.9 -m pip install --upgrade pip

# Create the directory for the Lambda layer
RUN mkdir -p /lambda/python/lib/python3.9/site-packages/

# Install psycopg2-binary into the correct directory for Python 3.9
RUN /usr/local/bin/python3.9 -m pip install psycopg2-binary -t /lambda/python/lib/python3.9/site-packages/


WORKDIR /lambda

# this is where from we can compress the file to .zip
CMD cp -r /lambda/python /output
